const PptxGenJS = require('pptxgenjs');
const path = require('path');
const fs = require('fs');
const os = require('os');

class PptGenerator {
  constructor() {
    this.tempDir = path.join(os.tmpdir(), 'ai-chat-ppt');
    if (!fs.existsSync(this.tempDir)) {
      fs.mkdirSync(this.tempDir, { recursive: true });
    }
  }

  async generate(pptData) {
    const pptx = new PptxGenJS();
    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'AI Chat Assistant';
    pptx.title = pptData.title || 'Presentation';

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: '1a1a2e' };
    titleSlide.addText(pptData.title || 'Untitled', {
      x: '10%', y: '35%', w: '80%', h: '30%',
      fontSize: 36, color: 'ffffff', bold: true,
      align: 'center', fontFace: 'Microsoft YaHei'
    });
    titleSlide.addText('Generated by AI Chat Assistant', {
      x: '10%', y: '65%', w: '80%', h: '10%',
      fontSize: 14, color: 'aaaaaa', align: 'center',
      fontFace: 'Microsoft YaHei'
    });

    // Content slides
    if (pptData.slides && Array.isArray(pptData.slides)) {
      for (const slide of pptData.slides) {
        const contentSlide = pptx.addSlide();
        contentSlide.background = { color: '16213e' };

        contentSlide.addText(slide.title || '', {
          x: '8%', y: '5%', w: '84%', h: '12%',
          fontSize: 28, color: '00d4ff', bold: true,
          fontFace: 'Microsoft YaHei'
        });

        if (slide.content && Array.isArray(slide.content)) {
          const bulletText = slide.content.map(item => ({
            text: item,
            options: {
              fontSize: 18,
              color: 'e0e0e0',
              bullet: { type: 'bullet', color: '00d4ff' },
              fontFace: 'Microsoft YaHei',
              breakLine: true,
              paraSpaceAfter: 12
            }
          }));

          contentSlide.addText(bulletText, {
            x: '10%', y: '22%', w: '80%', h: '70%',
            valign: 'top'
          });
        }
      }
    }

    const filename = `${pptData.title || 'presentation'}_${Date.now()}.pptx`;
    const safeName = filename.replace(/[<>:"/\\|?*]/g, '_');
    const filePath = path.join(this.tempDir, safeName);
    await pptx.writeFile({ fileName: filePath });

    return { filePath, filename: safeName };
  }

  detectPptxRequest(text) {
    const jsonMatch = text.match(/```json\s*([\s\S]*?)```/);
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[1].trim());
        if (parsed.type === 'pptx' && parsed.slides) {
          return parsed;
        }
      } catch (e) {
        // Not valid JSON
      }
    }
    return null;
  }
}

module.exports = PptGenerator;
