const PptxGenJS = require('pptxgenjs');
const path = require('path');
const fs = require('fs');
const os = require('os');

const DEFAULT_THEME = {
  primary: '1E2761',
  secondary: 'CADCFC',
  accent: '00D4FF',
  background: '0F1629',
  text: 'FFFFFF',
  mutedText: 'A0A0A0',
  headerFont: 'Georgia',
  bodyFont: 'Calibri'
};

class PptGenerator {
  constructor() {
    this.tempDir = path.join(os.tmpdir(), 'ai-chat-ppt');
    if (!fs.existsSync(this.tempDir)) {
      fs.mkdirSync(this.tempDir, { recursive: true });
    }
  }

  getTheme(pptData) {
    return { ...DEFAULT_THEME, ...(pptData.theme || {}) };
  }

  async generate(pptData) {
    const pptx = new PptxGenJS();
    const theme = this.getTheme(pptData);

    pptx.layout = 'LAYOUT_16x9';
    pptx.author = 'AI Chat Assistant';
    pptx.title = pptData.title || 'Presentation';

    this.addTitleSlide(pptx, pptData, theme);

    if (pptData.slides && Array.isArray(pptData.slides)) {
      for (const slideData of pptData.slides) {
        const layout = slideData.layout || 'bullets';
        switch (layout) {
          case 'stats':
            this.addStatsSlide(pptx, slideData, theme);
            break;
          case 'two-column':
            this.addTwoColumnSlide(pptx, slideData, theme);
            break;
          case 'chart':
            this.addChartSlide(pptx, slideData, theme);
            break;
          case 'timeline':
            this.addTimelineSlide(pptx, slideData, theme);
            break;
          default:
            this.addBulletsSlide(pptx, slideData, theme);
            break;
        }
      }
    }

    this.addEndSlide(pptx, theme);

    const filename = `${pptData.title || 'presentation'}_${Date.now()}.pptx`;
    const safeName = filename.replace(/[<>:"/\\|?*]/g, '_');
    const filePath = path.join(this.tempDir, safeName);
    await pptx.writeFile({ fileName: filePath });

    return { filePath, filename: safeName };
  }

  addTitleSlide(pptx, pptData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.primary };

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0, y: 0, w: '100%', h: '100%',
      fill: { color: theme.primary }
    });

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0, y: 4.8, w: '100%', h: 0.06,
      fill: { color: theme.accent }
    });

    slide.addText(pptData.title || 'Untitled', {
      x: 0.8, y: 1.5, w: 8.4, h: 2.0,
      fontSize: 40, color: theme.text, bold: true,
      fontFace: theme.headerFont, align: 'left', valign: 'middle',
      margin: 0
    });

    slide.addText('Generated by AI Chat Assistant', {
      x: 0.8, y: 4.2, w: 8.4, h: 0.5,
      fontSize: 12, color: theme.mutedText, align: 'left',
      fontFace: theme.bodyFont, margin: 0
    });
  }

  addBulletsSlide(pptx, slideData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0, y: 0, w: 0.06, h: '100%',
      fill: { color: theme.accent }
    });

    slide.addText(slideData.title || '', {
      x: 0.8, y: 0.3, w: 8.4, h: 0.7,
      fontSize: 28, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    if (slideData.content && Array.isArray(slideData.content)) {
      const bulletText = slideData.content.map((item, i) => ({
        text: item,
        options: {
          fontSize: 16,
          color: theme.text,
          bullet: { type: 'bullet', color: theme.accent },
          fontFace: theme.bodyFont,
          breakLine: true,
          paraSpaceAfter: 14
        }
      }));

      slide.addText(bulletText, {
        x: 1.0, y: 1.2, w: 8.0, h: 4.0,
        valign: 'top', margin: 0
      });
    }
  }

  addStatsSlide(pptx, slideData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    slide.addText(slideData.title || '', {
      x: 0.8, y: 0.3, w: 8.4, h: 0.7,
      fontSize: 28, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    const stats = slideData.stats || [];
    const count = Math.min(stats.length, 4);
    const cardWidth = (8.4 - (count - 1) * 0.3) / count;
    const startX = 0.8;

    for (let i = 0; i < count; i++) {
      const x = startX + i * (cardWidth + 0.3);
      const stat = stats[i];

      slide.addShape(pptx.shapes.RECTANGLE, {
        x, y: 1.5, w: cardWidth, h: 3.0,
        fill: { color: theme.primary },
        shadow: { type: 'outer', color: '000000', blur: 8, offset: 3, angle: 135, opacity: 0.3 }
      });

      slide.addShape(pptx.shapes.RECTANGLE, {
        x, y: 1.5, w: cardWidth, h: 0.06,
        fill: { color: theme.accent }
      });

      slide.addText(stat.value || '', {
        x, y: 1.8, w: cardWidth, h: 1.6,
        fontSize: 44, color: theme.accent, bold: true,
        fontFace: theme.headerFont, align: 'center', valign: 'middle',
        margin: 0
      });

      slide.addText(stat.label || '', {
        x, y: 3.4, w: cardWidth, h: 0.8,
        fontSize: 14, color: theme.mutedText,
        fontFace: theme.bodyFont, align: 'center', valign: 'top',
        margin: 0
      });
    }
  }

  addTwoColumnSlide(pptx, slideData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    slide.addText(slideData.title || '', {
      x: 0.8, y: 0.3, w: 8.4, h: 0.7,
      fontSize: 28, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    const colWidth = 4.0;
    const leftX = 0.8;
    const rightX = 5.2;

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: leftX, y: 1.2, w: colWidth, h: 3.8,
      fill: { color: theme.primary }
    });
    slide.addShape(pptx.shapes.RECTANGLE, {
      x: rightX, y: 1.2, w: colWidth, h: 3.8,
      fill: { color: theme.primary }
    });

    slide.addText(slideData.leftTitle || '', {
      x: leftX + 0.3, y: 1.4, w: colWidth - 0.6, h: 0.5,
      fontSize: 18, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    slide.addText(slideData.rightTitle || '', {
      x: rightX + 0.3, y: 1.4, w: colWidth - 0.6, h: 0.5,
      fontSize: 18, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    if (slideData.leftContent && Array.isArray(slideData.leftContent)) {
      const leftBullets = slideData.leftContent.map(item => ({
        text: item,
        options: {
          fontSize: 14, color: theme.text,
          bullet: { type: 'bullet', color: theme.accent },
          fontFace: theme.bodyFont, breakLine: true, paraSpaceAfter: 10
        }
      }));
      slide.addText(leftBullets, {
        x: leftX + 0.3, y: 2.0, w: colWidth - 0.6, h: 2.8,
        valign: 'top', margin: 0
      });
    }

    if (slideData.rightContent && Array.isArray(slideData.rightContent)) {
      const rightBullets = slideData.rightContent.map(item => ({
        text: item,
        options: {
          fontSize: 14, color: theme.text,
          bullet: { type: 'bullet', color: theme.accent },
          fontFace: theme.bodyFont, breakLine: true, paraSpaceAfter: 10
        }
      }));
      slide.addText(rightBullets, {
        x: rightX + 0.3, y: 2.0, w: colWidth - 0.6, h: 2.8,
        valign: 'top', margin: 0
      });
    }
  }

  addChartSlide(pptx, slideData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    slide.addText(slideData.title || '', {
      x: 0.8, y: 0.3, w: 8.4, h: 0.7,
      fontSize: 28, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    const chartData = slideData.chart;
    if (!chartData || !chartData.series) return;

    const chartType = this.getChartType(pptx, chartData.type);
    const seriesData = chartData.series.map(s => ({
      name: s.name || '',
      labels: s.labels || [],
      values: s.values || []
    }));

    const chartColors = [theme.accent, theme.secondary, 'F96167', 'F9E795', '97BC62'];

    slide.addChart(chartType, seriesData, {
      x: 0.8, y: 1.2, w: 8.4, h: 4.0,
      barDir: chartData.type === 'bar' ? 'col' : undefined,
      chartColors: chartColors.slice(0, seriesData.length || 1),
      chartArea: { fill: { color: theme.primary }, roundedCorners: true },
      catAxisLabelColor: theme.mutedText,
      valAxisLabelColor: theme.mutedText,
      catAxisLabelFontFace: theme.bodyFont,
      valAxisLabelFontFace: theme.bodyFont,
      valGridLine: { color: theme.background, size: 0.5 },
      catGridLine: { style: 'none' },
      showValue: chartData.type !== 'pie',
      showPercent: chartData.type === 'pie',
      dataLabelColor: theme.text,
      showLegend: seriesData.length > 1,
      legendColor: theme.mutedText,
      legendFontFace: theme.bodyFont
    });
  }

  getChartType(pptx, type) {
    switch (type) {
      case 'line': return pptx.charts.LINE;
      case 'pie': return pptx.charts.PIE;
      case 'doughnut': return pptx.charts.DOUGHNUT;
      default: return pptx.charts.BAR;
    }
  }

  addTimelineSlide(pptx, slideData, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.background };

    slide.addText(slideData.title || '', {
      x: 0.8, y: 0.3, w: 8.4, h: 0.7,
      fontSize: 28, color: theme.accent, bold: true,
      fontFace: theme.headerFont, margin: 0
    });

    const steps = slideData.steps || [];
    const count = Math.min(steps.length, 5);
    const lineY = 2.8;

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 1.0, y: lineY, w: 8.0, h: 0.04,
      fill: { color: theme.accent }
    });

    const spacing = 8.0 / (count > 1 ? count - 1 : 1);

    for (let i = 0; i < count; i++) {
      const step = steps[i];
      const cx = 1.0 + i * spacing;
      const circleSize = 0.4;

      slide.addShape(pptx.shapes.OVAL, {
        x: cx - circleSize / 2, y: lineY - circleSize / 2 + 0.02,
        w: circleSize, h: circleSize,
        fill: { color: theme.accent }
      });

      slide.addText(String(i + 1), {
        x: cx - circleSize / 2, y: lineY - circleSize / 2 + 0.02,
        w: circleSize, h: circleSize,
        fontSize: 14, color: theme.primary, bold: true,
        fontFace: theme.bodyFont, align: 'center', valign: 'middle',
        margin: 0
      });

      slide.addText(step.title || '', {
        x: cx - 1.0, y: lineY + 0.5, w: 2.0, h: 0.5,
        fontSize: 14, color: theme.text, bold: true,
        fontFace: theme.headerFont, align: 'center', valign: 'top',
        margin: 0
      });

      slide.addText(step.description || '', {
        x: cx - 1.0, y: lineY + 1.0, w: 2.0, h: 0.8,
        fontSize: 11, color: theme.mutedText,
        fontFace: theme.bodyFont, align: 'center', valign: 'top',
        margin: 0
      });
    }
  }

  addEndSlide(pptx, theme) {
    const slide = pptx.addSlide();
    slide.background = { color: theme.primary };

    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0, y: 2.6, w: '100%', h: 0.06,
      fill: { color: theme.accent }
    });

    slide.addText('谢谢观看', {
      x: 0.8, y: 1.5, w: 8.4, h: 1.5,
      fontSize: 36, color: theme.text, bold: true,
      fontFace: theme.headerFont, align: 'center', valign: 'middle',
      margin: 0
    });

    slide.addText('AI Chat Assistant', {
      x: 0.8, y: 3.2, w: 8.4, h: 0.6,
      fontSize: 14, color: theme.mutedText,
      fontFace: theme.bodyFont, align: 'center', valign: 'top',
      margin: 0
    });
  }

  detectPptxRequest(text) {
    const jsonMatch = text.match(/```json\s*([\s\S]*?)```/);
    if (jsonMatch) {
      try {
        const parsed = JSON.parse(jsonMatch[1].trim());
        if (parsed.type === 'pptx' && parsed.slides) {
          return parsed;
        }
      } catch (e) {
        // Not valid JSON
      }
    }
    return null;
  }
}

module.exports = PptGenerator;
